[package]
name = "revvy02/miu-ui-labs"
description = "UI Labs storybook integration for miu"
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/**", "wally.toml", "default.project.json", "LICENSE"]

[dependencies]
miu = "revvy02/miu@0.1.0"
ui_labs = "pepeeltoro41/ui-labs@2.3.8"
