name = "rvy/miu"
version = "0.1.0"
license = "MIT"
private = true

[engines]
pesde = "^0.7.2"

[target]
environment = "roblox"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
retained_scope = { wally = "revvy02/retained-scope", version = "^0.1.0" }
